# Generated by Django 4.2.4 on 2023-08-27 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voting_window_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 21, 6, 9, 91061)),
        ),
    ]
