# Generated by Django 4.2.4 on 2023-08-27 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_vote_voting_window_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='voting_window_end',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voting_window_start',
        ),
        migrations.AddField(
            model_name='singer',
            name='voting_window_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 21, 21, 45, 695353)),
        ),
        migrations.AddField(
            model_name='singer',
            name='voting_window_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 0, 0)),
        ),
    ]
